import { createContext, useContext, useState, useCallback } from "react";
import type { ReactNode } from "react";

type Lang = "ru" | "en";

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    home: "Главная",
    catalog: "Каталог",
    sell: "Продать",
    messages: "Чаты",
    profile: "Профиль",
    deals: "Сделки",
    wallet: "Кошелёк",
    settings: "Настройки",
    favorites: "Избранное",
    admin: "Админ",
    logout: "Выйти",
    login: "Войти",
    register: "Регистрация",
    search: "Поиск...",
    price: "Цена",
    buy: "Купить",
    soldCount: "Продано",
    views: "Просмотров",
    rating: "Рейтинг",
    reviews: "Отзывы",
    noProducts: "Нет товаров",
    loading: "Загрузка...",
    error: "Ошибка",
    save: "Сохранить",
    cancel: "Отмена",
    back: "Назад",
    balance: "Баланс",
    deposit: "Пополнить",
    withdraw: "Вывести",
    amount: "Сумма",
    transactions: "Транзакции",
    secureDeal: "Безопасная сделка",
    description: "Описание",
    category: "Категория",
    title: "Название",
    images: "Изображения",
    tags: "Теги",
    deliveryType: "Тип доставки",
    auto: "Автоматическая",
    manual: "Ручная",
    create: "Создать",
    update: "Обновить",
    delete: "Удалить",
    confirm: "Подтвердить",
    dispute: "Спор",
    deliver: "Доставить",
    completed: "Завершено",
    pending: "Ожидание",
    paid: "Оплачено",
    delivered: "Доставлено",
    disputed: "Спор",
    cancelled: "Отменено",
    refunded: "Возврат",
    writeMessage: "Написать...",
    send: "Отправить",
    online: "Онлайн",
    totalUsers: "Всего пользователей",
    totalProducts: "Всего товаров",
    totalDeals: "Всего сделок",
    featuredProducts: "Рекомендуемые",
    recentProducts: "Новые товары",
    allCategories: "Все категории",
    username: "Имя пользователя",
    password: "Пароль",
    authCode: "Код авторизации",
    requestCode: "Получить код",
    enterCode: "Введите код из Telegram бота",
    telegramBot: "Telegram бот",
    paymentMethod: "Способ оплаты",
    withdrawMethod: "Способ вывода",
    withdrawDetails: "Реквизиты",
    minAmount: "Минимальная сумма",
    gameAccounts: "Игровые аккаунты",
    gameItems: "Игровые предметы",
    gameCurrency: "Игровая валюта",
    boosting: "Бустинг",
    services: "Услуги",
    other: "Другое",
    verified: "Проверен",
    seller: "Продавец",
    buyer: "Покупатель",
    dealNumber: "Сделка #",
    commission: "Комиссия",
    sellerLevel: "Уровень продавца",
    newcomer: "Новичок",
    beginner: "Начинающий",
    experienced: "Опытный",
    professional: "Профессионал",
    expert: "Эксперт",
    ban: "Забанить",
    unban: "Разбанить",
    verify: "Верифицировать",
    moderate: "Модерация",
    approve: "Одобрить",
    reject: "Отклонить",
    resolve: "Решить",
    refundBuyer: "Возврат покупателю",
    paySeller: "Оплата продавцу",
    processWithdrawal: "Обработать вывод",
    stats: "Статистика",
    revenue: "Доход",
    today: "Сегодня",
    pendingWithdrawals: "Ожидающие выводы",
    activeDisputes: "Активные споры",
    sort: "Сортировка",
    newest: "Новые",
    cheapest: "Дешёвые",
    expensive: "Дорогие",
    popular: "Популярные",
    filters: "Фильтры",
    priceRange: "Диапазон цен",
    from: "От",
    to: "До",
    apply: "Применить",
    reset: "Сбросить",
    noResults: "Ничего не найдено",
    game: "Игра",
    server: "Сервер",
    language: "Язык",
    ru: "Русский",
    en: "English",
    bio: "О себе",
    firstName: "Имя",
    lastName: "Фамилия",
    avatar: "Аватар",
    editProfile: "Редактировать профиль",
    myProducts: "Мои товары",
    addProduct: "Добавить товар",
    dealDetails: "Детали сделки",
    leaveReview: "Оставить отзыв",
    comment: "Комментарий",
    all: "Все",
    active: "Активные",
    hidden: "Скрытые",
    rejected: "Отклонённые",
    frozen: "Заморожено",
    totalDeposited: "Всего пополнено",
    totalWithdrawn: "Всего выведено",
    totalEarned: "Всего заработано",
    rub: "руб.",
    noMessages: "Нет сообщений",
    noDeals: "Нет сделок",
    noReviews: "Нет отзывов",
    noTransactions: "Нет транзакций",
    productCreated: "Товар создан",
    productUpdated: "Товар обновлён",
    depositCreated: "Депозит создан",
    withdrawCreated: "Заявка на вывод создана",
    dealCreated: "Сделка создана",
    reviewSent: "Отзыв отправлен",
    messageSent: "Сообщение отправлено",
    profileUpdated: "Профиль обновлён",
    codeSent: "Код готов — напишите /start боту",
    loginSuccess: "Вход выполнен",
    registerSuccess: "Регистрация выполнена",
    insufficientFunds: "Недостаточно средств",
    categories: "Категории",
    users: "Пользователи",
    products: "Товары",
    withdrawals: "Выводы",
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    sell: "Sell",
    messages: "Messages",
    profile: "Profile",
    deals: "Deals",
    wallet: "Wallet",
    settings: "Settings",
    favorites: "Favorites",
    admin: "Admin",
    logout: "Logout",
    login: "Login",
    register: "Register",
    search: "Search...",
    price: "Price",
    buy: "Buy",
    soldCount: "Sold",
    views: "Views",
    rating: "Rating",
    reviews: "Reviews",
    noProducts: "No products",
    loading: "Loading...",
    error: "Error",
    save: "Save",
    cancel: "Cancel",
    back: "Back",
    balance: "Balance",
    deposit: "Deposit",
    withdraw: "Withdraw",
    amount: "Amount",
    transactions: "Transactions",
    secureDeal: "Secure deal",
    description: "Description",
    category: "Category",
    title: "Title",
    images: "Images",
    tags: "Tags",
    deliveryType: "Delivery type",
    auto: "Automatic",
    manual: "Manual",
    create: "Create",
    update: "Update",
    delete: "Delete",
    confirm: "Confirm",
    dispute: "Dispute",
    deliver: "Deliver",
    completed: "Completed",
    pending: "Pending",
    paid: "Paid",
    delivered: "Delivered",
    disputed: "Disputed",
    cancelled: "Cancelled",
    refunded: "Refunded",
    writeMessage: "Write a message...",
    send: "Send",
    online: "Online",
    totalUsers: "Total users",
    totalProducts: "Total products",
    totalDeals: "Total deals",
    featuredProducts: "Featured",
    recentProducts: "New products",
    allCategories: "All categories",
    username: "Username",
    password: "Password",
    authCode: "Auth code",
    requestCode: "Get code",
    enterCode: "Enter code from Telegram bot",
    telegramBot: "Telegram bot",
    paymentMethod: "Payment method",
    withdrawMethod: "Withdrawal method",
    withdrawDetails: "Details",
    minAmount: "Min amount",
    gameAccounts: "Game accounts",
    gameItems: "Game items",
    gameCurrency: "Game currency",
    boosting: "Boosting",
    services: "Services",
    other: "Other",
    verified: "Verified",
    seller: "Seller",
    buyer: "Buyer",
    dealNumber: "Deal #",
    commission: "Commission",
    sellerLevel: "Seller level",
    newcomer: "Newcomer",
    beginner: "Beginner",
    experienced: "Experienced",
    professional: "Professional",
    expert: "Expert",
    ban: "Ban",
    unban: "Unban",
    verify: "Verify",
    moderate: "Moderate",
    approve: "Approve",
    reject: "Reject",
    resolve: "Resolve",
    refundBuyer: "Refund buyer",
    paySeller: "Pay seller",
    processWithdrawal: "Process withdrawal",
    stats: "Stats",
    revenue: "Revenue",
    today: "Today",
    pendingWithdrawals: "Pending withdrawals",
    activeDisputes: "Active disputes",
    sort: "Sort",
    newest: "Newest",
    cheapest: "Cheapest",
    expensive: "Expensive",
    popular: "Popular",
    filters: "Filters",
    priceRange: "Price range",
    from: "From",
    to: "To",
    apply: "Apply",
    reset: "Reset",
    noResults: "No results",
    game: "Game",
    server: "Server",
    language: "Language",
    ru: "Russian",
    en: "English",
    bio: "Bio",
    firstName: "First name",
    lastName: "Last name",
    avatar: "Avatar",
    editProfile: "Edit profile",
    myProducts: "My products",
    addProduct: "Add product",
    dealDetails: "Deal details",
    leaveReview: "Leave review",
    comment: "Comment",
    all: "All",
    active: "Active",
    hidden: "Hidden",
    rejected: "Rejected",
    frozen: "Frozen",
    totalDeposited: "Total deposited",
    totalWithdrawn: "Total withdrawn",
    totalEarned: "Total earned",
    rub: "RUB",
    noMessages: "No messages",
    noDeals: "No deals",
    noReviews: "No reviews",
    noTransactions: "No transactions",
    productCreated: "Product created",
    productUpdated: "Product updated",
    depositCreated: "Deposit created",
    withdrawCreated: "Withdrawal request created",
    dealCreated: "Deal created",
    reviewSent: "Review sent",
    messageSent: "Message sent",
    profileUpdated: "Profile updated",
    codeSent: "Code ready — send /start to the bot",
    loginSuccess: "Login successful",
    registerSuccess: "Registration successful",
    insufficientFunds: "Insufficient funds",
    categories: "Categories",
    users: "Users",
    products: "Products",
    withdrawals: "Withdrawals",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem("mm_lang") as Lang) || "ru");

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("mm_lang", l);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used inside LangProvider");
  return ctx;
}
